```yaml
name: tollmateai_native_ui

description: Native Flutter app for FastAPI integration

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  http: ^0.13.5

flutter:
  uses-material-design: true
